### ISSUE TITLE
Doesn't run

### ISSUE THREAD

**Issue by dfabulich** [ericzundel/mvn2pants#1]
There's no documentation explaining how to use this project, but I tried this:

```
git clone https://github.com/ericzundel/mvn2pants.git
cd mvn2pants
curl -O https://pantsbuild.github.io/setup/pants
chmod +x pants
touch pants.ini
./pants run src/python/squarepants:pom_to_build
```

It didn't work. Here's the error I get:

```
INFO] Detected git repository at /private/tmp/tp/mvn2pants on branch master

15:18:08 00:00 [main]
               (To run a reporting server: ./pants server)
15:18:08 00:00   [setup]
15:18:08 00:00     [parse]
               Executing tasks in goals: bootstrap -> imports -> unpack-jars -> deferred-sources -> gen -> jvm-platform-validate -> resolve -> compile -> resources -> run
15:18:08 00:00   [bootstrap]
15:18:08 00:00     [bootstrap-jvm-tools]
15:18:08 00:00   [imports]
15:18:08 00:00     [ivy-imports]
15:18:08 00:00   [unpack-jars]
15:18:08 00:00     [unpack-jars]
15:18:08 00:00   [deferred-sources]
15:18:08 00:00     [deferred-sources]
15:18:08 00:00   [gen]
15:18:08 00:00     [thrift]
15:18:08 00:00     [protoc]
15:18:08 00:00     [antlr]
15:18:08 00:00     [ragel]
15:18:08 00:00     [jaxb]
15:18:08 00:00     [wire]
15:18:08 00:00   [jvm-platform-validate]
15:18:08 00:00     [jvm-platform-validate]
15:18:08 00:00   [resolve]
15:18:08 00:00     [ivy]
15:18:08 00:00   [compile]
15:18:08 00:00     [compile-jvm-prep-command]
15:18:08 00:00       [jvm_prep_command]
15:18:08 00:00     [compile]
15:18:08 00:00     [zinc]
15:18:08 00:00     [jvm-dep-check]
15:18:08 00:00   [resources]
15:18:08 00:00     [prepare]
15:18:08 00:00     [services]
15:18:08 00:00   [run]
15:18:08 00:00     [py]
15:18:08 00:00       [run]
Traceback (most recent call last):
  File "/private/tmp/tp/mvn2pants/.pants.d/python-setup/chroots/778f94b076e5da9664d04468f6276ebb2eb446ff/.bootstrap/_pex/pex.py", line 317, in execute
    self._wrap_coverage(self._wrap_profiling, self._execute)
  File "/private/tmp/tp/mvn2pants/.pants.d/python-setup/chroots/778f94b076e5da9664d04468f6276ebb2eb446ff/.bootstrap/_pex/pex.py", line 250, in _wrap_coverage
    runner(*args)
  File "/private/tmp/tp/mvn2pants/.pants.d/python-setup/chroots/778f94b076e5da9664d04468f6276ebb2eb446ff/.bootstrap/_pex/pex.py", line 282, in _wrap_profiling
    runner(*args)
  File "/private/tmp/tp/mvn2pants/.pants.d/python-setup/chroots/778f94b076e5da9664d04468f6276ebb2eb446ff/.bootstrap/_pex/pex.py", line 360, in _execute
    return self.execute_entry(self._pex_info.entry_point)
  File "/private/tmp/tp/mvn2pants/.pants.d/python-setup/chroots/778f94b076e5da9664d04468f6276ebb2eb446ff/.bootstrap/_pex/pex.py", line 418, in execute_entry
    runner(entry_point)
  File "/private/tmp/tp/mvn2pants/.pants.d/python-setup/chroots/778f94b076e5da9664d04468f6276ebb2eb446ff/.bootstrap/_pex/pex.py", line 423, in execute_module
    runpy.run_module(module_name, run_name='__main__')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 180, in run_module
    fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/private/tmp/tp/mvn2pants/.pants.d/python-setup/chroots/778f94b076e5da9664d04468f6276ebb2eb446ff/squarepants/pom_to_build.py", line 25, in <module>
    from pom_file import PomFile
ImportError: No module named pom_file

FAILURE: /usr/bin/python squarepants.pom_to_build  ... exited non-zero (1)


15:18:08 00:00   [complete]
               FAILURE
```

I assume I'm just not using the project correctly. What am I missing?

**Comment by stuhood** [comment]
@dfabulich : It looks like the BUILD files in the `src/python/squarepants` directory are probably something of a lie.

I was able to run `src/python/squarepants/pom_to_BUILD.py ${path_to}/pom.xml` successfully though.

**Comment by ericzundel** [comment]
Sorry, this is a code dump from our repo. I've never tried to run it
standalone. It has lots of square-isms in it.
